# Generated by Django 5.0.4 on 2026-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('returned', 'Returned'), ('not_returned', 'Not Returned')], default='pending', max_length=20),
        ),
    ]
