# Generated by Django 5.0.4 on 2026-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_extension',
            field=models.BooleanField(default=False),
        ),
    ]
