# Generated by Django 5.0.4 on 2026-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
