# Generated by Django 5.0.4 on 2026-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_is_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('new_booking', 'New Booking'), ('booking_update', 'Booking Update'), ('booking_extension', 'Booking Extension'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined')], max_length=30)),
                ('booking_id', models.IntegerField()),
                ('resource_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
