# Generated by Django 5.0.4 on 2026-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('not_returned', 'Not Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('booking_update', 'Booking Update'), ('booking_extension', 'Booking Extension'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled')], max_length=30),
        ),
    ]
