# Generated by Django 5.0.4 on 2026-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('for_pickup', 'For Pick Up'), ('not_returned', 'Not Returned'), ('returned', 'Returned'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
