# Generated by Django 5.0.4 on 2026-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
