# Generated by Django 5.0.4 on 2026-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_original_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('for_pickup', 'For Pick Up'), ('not_returned', 'Not Returned'), ('returned', 'Returned'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('no_pickup', 'No Pick Up')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('booking_update', 'Booking Update'), ('booking_extension', 'Booking Extension'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_picked_up', 'Booking Picked Up'), ('booking_no_pickup', 'Booking No Pick Up')], max_length=30),
        ),
    ]
