# Generated by Django 5.0.4 on 2026-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_end_time_booking_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('booking_update', 'Booking Update'), ('booking_extension', 'Booking Extension'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_picked_up', 'Booking Picked Up'), ('booking_no_pickup', 'Booking No Pick Up'), ('booking_reminder', 'Booking Reminder')], max_length=30),
        ),
    ]
