# Generated by Django 5.0.4 on 2026-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_notification_type'),
    ]

    operations = [
    ]
