# Generated by Django 5.0.4 on 2026-04-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_notification_type_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity_requested',
            field=models.IntegerField(default=1),
        ),
    ]
