# Generated by Django 5.0.4 on 2026-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_quantity_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('resource_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=20)),
                ('reported_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'damage_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('booking_update', 'Booking Update'), ('booking_extension', 'Booking Extension'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_picked_up', 'Booking Picked Up'), ('booking_no_pickup', 'Booking No Pick Up'), ('booking_reminder', 'Booking Reminder'), ('damage_report', 'Damage Report')], max_length=30),
        ),
    ]
